repos:
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
    -   id: gitlint
        args: [--contrib=CT1, --ignore=B6,  --msg-filename]
    -   id: gitlint-ci
        args: [--contrib=CT1, --ignore=B6, -c general.ignore-by-author-name.regex=github-actions, --msg-filename]
